### ISSUE TITLE
Not confirm

### ISSUE THREAD

**Issue by leandrogomesmachado** [MatthewLM/peercoinj#1]
Hello I send made a Android Wallet based on your Android system, named htmlcoinj and htmlcoin-android-wallet that you can see here:
https://github.com/machado-rev/htmlcoinj
https://github.com/machado-rev/htmlcoin-android-wallet

THe unic problem is: I send from my computer to the Android Wallet, receive on the Phone but never confirm to be spendable.

What I need to do? I will update my github with my changes.

thanks

**Comment by leandrogomesmachado** [comment]
@MatthewLM the updated was sent, are on my github, did you know what I need to do to solve the confirmation problems?
All data seems to be ok.

Thanks

**Comment by MatthewLM** [comment]
Hi. To determine the problem, you should take a look first of all at the logcat output to see what block verification errors are occurring if any. You may have to use a Java debugger to figure out the part of code responsible.

**Comment by leandrogomesmachado** [comment]
Hello, thank you for reply, so I never do java programs, I have no experience to debug. What tools you recommend? I and stuckied on this last step on Htmlcoin, on Kobocoin I need change some things before continue. Thanks

**Comment by MatthewLM** [comment]
I personally use netbeans which has a good debugger. You need to import the code as a project and then attach the debugger to the app running on your connected device.

**Comment by leandrogomesmachado** [comment]
Goes to here, because are located on Android Wallet:
https://github.com/MatthewLM/peercoin-android-wallet/issues/10
